import { Montserrat } from "next/font/google";
import "./global.css";
// import { ThemeProviderContext } from "@/utils/themeContext";
import { ThemeProviderContext } from "../utils/themeContext.jsx";
import AppHeader from "../components/AppHeader/index.jsx";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sparsh Jain",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProviderContext>
      <html lang="en">
        <body className={`${montserrat.variable} antialiased`}>
          <AppHeader />
          {children}
        </body>
      </html>
    </ThemeProviderContext>
  );
}
